name: Build ESP32-C3 SuperMini

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: arduino/setup-arduino-cli@v1

      - run: |
          arduino-cli core update-index
          arduino-cli core install esp32:esp32

      - run: |
          arduino-cli compile \
          --fqbn esp32:esp32:esp32c3 \
          --output-dir build \
          blink.ino

      - uses: actions/upload-artifact@v4
        with:
          name: esp32c3-build
          path: build